# Global settings
title: tim's dashboard
favicon: https://nixos.org/favicon.ico
background: https://images.unsplash.com/photo-1672288072591-619afe830096?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80
backgroundOpacity: 0.5
theme: dark
color: slate

# Header settings
header: true
headerStyle: boxed
navbar: true

# Layout
layout:
  Books:
    style: column
    columns: 4
  Auth:
    style: column
    columns: 4
  Cloud:
    style: column
    columns: 4
  Media:
    style: column
    columns: 4
  Game Servers:
    style: column
    columns: 4
  PDS:
    style: column
    columns: 4

# Quicklaunch
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google
